# Generated by Django 2.1.4 on 2019-07-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='questions',
            field=models.ManyToManyField(to='civil_cultural.Question'),
        ),
        migrations.AddField(
            model_name='article',
            name='reports',
            field=models.ManyToManyField(to='civil_cultural.Report'),
        ),
        migrations.AddField(
            model_name='portal',
            name='rules',
            field=models.ManyToManyField(to='civil_cultural.Rule'),
        ),
        migrations.AddField(
            model_name='portal',
            name='topics',
            field=models.ManyToManyField(to='civil_cultural.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='articles',
            field=models.ManyToManyField(to='civil_cultural.Article'),
        ),
    ]
