# Generated by Django 2.1.4 on 2019-07-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0002_auto_20190710_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='similar_suggestions',
            field=models.ManyToManyField(to='civil_cultural.SimilarSuggestion'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='civil_cultural.Tag'),
        ),
        migrations.AddField(
            model_name='portal',
            name='tags',
            field=models.ManyToManyField(to='civil_cultural.Tag'),
        ),
    ]
