# Generated by Django 2.1.4 on 2019-07-12 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0004_topic_topic_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='civil_cultural.Topic'),
            preserve_default=False,
        ),
    ]
