# Generated by Django 2.1.4 on 2019-07-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0006_question_published_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='portal_reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='civil_cultural.Portal'),
            preserve_default=False,
        ),
    ]
