# Generated by Django 2.1.4 on 2019-07-15 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0009_auto_20190714_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='portal',
            new_name='portal_reference',
        ),
    ]
