# Generated by Django 2.1.4 on 2019-07-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0010_auto_20190715_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('description', 'portal_reference')},
        ),
    ]
