# Generated by Django 2.1.4 on 2019-07-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0012_news_similar_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarsuggestion',
            name='post_key',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='similarsuggestion',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='similarsuggestion',
            unique_together={('link', 'post_key')},
        ),
    ]
