# Generated by Django 2.1.4 on 2019-07-18 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civil_cultural', '0013_auto_20190715_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('pro_votes', models.IntegerField(default=0)),
                ('cons_votes', models.IntegerField(default=0)),
                ('publish_datetime', models.DateTimeField(auto_now_add=True)),
                ('post_key', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil_cultural.Question')),
            ],
        ),
    ]
