# Generated by Django 2.1.4 on 2019-07-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_cultural', '0014_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='post_key',
        ),
    ]
