# Generated by Django 2.1.4 on 2019-09-27 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civil_cultural', '0015_remove_answer_post_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
