# Generated by Django 2.1.4 on 2019-09-27 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civil_cultural', '0016_portal_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portal_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
